# Generated by Django 5.2.1 on 2025-06-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(default='https://res.cloudinary.com/dj5p9ubcu/image/upload/v1750632467/default_post_ltnkan', max_length=500),
        ),
    ]
