# Generated by Django 5.2.1 on 2025-06-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/DEIN_CLOUD_NAME/image/upload/v1234567890/default_profile_rxsxdv.jpg', upload_to='images/'),
        ),
    ]
