# Generated by Django 5.2.1 on 2025-06-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_rxsxdv', upload_to='images/'),
        ),
    ]
