# Generated by Django 4.2 on 2025-09-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0002_alter_draft_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
