# Generated by Django 4.2 on 2025-09-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drafts", "0003_draft_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="draft",
            name="scheduled_time",
        ),
        migrations.AlterField(
            model_name="draft",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=10,
            ),
        ),
    ]
